/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package servidorDeNotificaciones.vistas;

import servidorDeNotificaciones.dto.Pedido;

/**
 *
 * @author JUAN
 */
public class vistaNotificacion extends javax.swing.JFrame {

    String atrMatrix[][];

    int pos = 0;

    /**
     * Creates new form vistaNotificacion
     */
    public vistaNotificacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNotificaciones = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNotificaciones = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNotificaciones.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblNotificaciones.setText("NOTFICACIONES DE PEDIDOS");

        tblNotificaciones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblNotificaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "# MESA", "#HAMBURGUESA", "TIPO", "INGREDIENTES EXTRA"
            }
        ));
        tblNotificaciones.setGridColor(new java.awt.Color(186, 52, 52));
        jScrollPane1.setViewportView(tblNotificaciones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(lblNotificaciones)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNotificaciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNotificaciones;
    private javax.swing.JTable tblNotificaciones;
    // End of variables declaration//GEN-END:variables

    public void notificarTabla(Pedido objPedido) {
        int limite = pos + objPedido.getListaHamburguesas().size();
        int contador = 0;
        String Matrix[][] = new String[limite][4];

        for (int i = 0; i < pos; i++) {
            Matrix[i][0] = atrMatrix[i][0];
            Matrix[i][1] = atrMatrix[i][1];
            Matrix[i][2] = atrMatrix[i][2];
            Matrix[i][3] = atrMatrix[i][3];
        }

        for (int i = 0; i < objPedido.getListaHamburguesas().size(); i++) {
            Matrix[pos][0] = objPedido.getMesa();
            Matrix[pos][1] = "" + (i + 1);

            switch (objPedido.getListaHamburguesas().get(i).getTipo()) {
                case 'P':
                    Matrix[pos][2] = "PEQUEÑA";
                    break;
                case 'M':
                    Matrix[pos][2] = "MEDIANA";
                    break;
                case 'G':
                    Matrix[pos][2] = "GRANDE";
                    break;
                default:
                    break;
            }

            Matrix[pos][3] = "" + objPedido.getListaHamburguesas().get(i).getCantidadIngredientesExtra();
            pos++;

        }
        tblNotificaciones.setModel(new javax.swing.table.DefaultTableModel(
                Matrix,
                new String[]{
                    "# MESA", "#HAMBURGUESA", "TIPO", "INGREDIENTES EXTRA"
                }
        ));
        atrMatrix = Matrix;
    }

}
