/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cliente.vistas;

import java.rmi.RemoteException;
import servidorDePedidos.dto.DatosEmpresas;

/**
 *
 * @author JUAN
 */
public class VistaDatos extends javax.swing.JInternalFrame {

    DatosEmpresas atrEmpresa;

    /**
     * Creates new form VistaDatos
     *
     * @param objEmpresa
     * @throws java.rmi.RemoteException
     */
    public VistaDatos(DatosEmpresas objEmpresa) throws RemoteException {
        initComponents();
        atrEmpresa = objEmpresa;
        llenarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblNit = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        lblPequenia = new javax.swing.JLabel();
        lblMediana = new javax.swing.JLabel();
        lblGrande = new javax.swing.JLabel();
        lblIngrediente = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setTitle("Datos Empresa");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("CHUBBY BURGUER");

        lblNit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNit.setText("NIT: ");

        lblPrecio.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblPrecio.setText("PRECIOS DE LAS HAMBURGUESAS");

        lblPequenia.setText("PEQUEÑA: $  ");

        lblMediana.setText("MEDIANA: $ ");

        lblGrande.setText("GRANDE: $");

        lblIngrediente.setText("VALOR INGREDIENTES EXTRA : $  ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblIngrediente)
                        .addComponent(lblMediana)
                        .addComponent(lblGrande)
                        .addComponent(lblPequenia)
                        .addComponent(lblNit)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPrecio)
                        .addGap(8, 8, 8)))
                .addGap(138, 138, 138))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblNit)
                .addGap(18, 18, 18)
                .addComponent(lblPrecio)
                .addGap(18, 18, 18)
                .addComponent(lblPequenia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMediana)
                .addGap(15, 15, 15)
                .addComponent(lblGrande)
                .addGap(18, 18, 18)
                .addComponent(lblIngrediente)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void llenarDatos(DatosEmpresas objEmpresa) {
        lblNit.setText(lblNit.getText() + " " + objEmpresa.getNit());
        lblPrecio.setText(lblPrecio.getText() + " " + objEmpresa.getValorIngredienteExtra());
        lblPequenia.setText(lblPequenia.getText() + "" + objEmpresa.getValorTipoHamburguesaP());
        lblMediana.setText(lblMediana.getText() + "" + objEmpresa.getValorTipoHamburguesaM());
        lblGrande.setText(lblGrande.getText() + " " + objEmpresa.getValorTipoHamburguesaG());
        objEmpresa.setValorTipoHamburguesaP(objEmpresa.getValorTipoHamburguesaP());

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblGrande;
    private javax.swing.JLabel lblIngrediente;
    private javax.swing.JLabel lblMediana;
    private javax.swing.JLabel lblNit;
    private javax.swing.JLabel lblPequenia;
    private javax.swing.JLabel lblPrecio;
    // End of variables declaration//GEN-END:variables

    private void llenarDatos() {
        lblNit.setText(lblNit.getText() + "" + atrEmpresa.getNit());
        lblIngrediente.setText(lblIngrediente.getText() + "" + atrEmpresa.getValorIngredienteExtra());
        lblGrande.setText(lblGrande.getText() + " " + atrEmpresa.getValorTipoHamburguesaG());
        lblMediana.setText(lblMediana.getText() + " " + atrEmpresa.getValorTipoHamburguesaM());
        lblPequenia.setText(lblPequenia.getText() + " " + atrEmpresa.getValorTipoHamburguesaP());
    }
}
